/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.poo2.gui.panel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ufps.poo2.gui.controlador.Controlador;

/**
 *
 * @author USUARIO
 */
public class FormJuego extends javax.swing.JFrame {

    /**
     * Creates new form Bag
     */
    Controlador controlador;
    FormSala sala;

    public FormJuego(int tam, FormSala s) {
        initComponents();
        controlador = new Controlador();
        iniciar(tam);
        mostrarPuntos();
        sala = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        panelJuego = new javax.swing.JPanel();
        chat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        txtMensaje = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmdGuardarChat = new javax.swing.JButton();
        cmdCargarChat = new javax.swing.JButton();
        cmdAdjuntar = new javax.swing.JButton();
        panelPuntos = new javax.swing.JPanel();
        lblJugador1 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();
        lblPunto2 = new javax.swing.JLabel();
        lblPunto1 = new javax.swing.JLabel();
        lblPunto4 = new javax.swing.JLabel();
        lblPunto3 = new javax.swing.JLabel();
        panelOtros = new javax.swing.JPanel();
        cmdJugadoresActivos = new javax.swing.JButton();
        cmdAcabar = new javax.swing.JButton();
        lblGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "CAMPO"));

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        chat.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CHAT"));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setLineWrap(true);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        txtMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeActionPerformed(evt);
            }
        });

        jButton1.setText("enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmdGuardarChat.setText("Guardar Chat");
        cmdGuardarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarChatActionPerformed(evt);
            }
        });

        cmdCargarChat.setText("Cargar Chat");
        cmdCargarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCargarChatActionPerformed(evt);
            }
        });

        cmdAdjuntar.setText("Adjuntar");
        cmdAdjuntar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdAdjuntarMouseMoved(evt);
            }
        });
        cmdAdjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdjuntarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chatLayout = new javax.swing.GroupLayout(chat);
        chat.setLayout(chatLayout);
        chatLayout.setHorizontalGroup(
            chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(chatLayout.createSequentialGroup()
                        .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chatLayout.createSequentialGroup()
                                .addComponent(cmdGuardarChat)
                                .addGap(18, 18, 18)
                                .addComponent(cmdCargarChat)
                                .addGap(18, 18, 18)
                                .addComponent(cmdAdjuntar))
                            .addGroup(chatLayout.createSequentialGroup()
                                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        chatLayout.setVerticalGroup(
            chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(1, 1, 1)
                .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdAdjuntar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdGuardarChat)
                        .addComponent(cmdCargarChat)))
                .addContainerGap())
        );

        panelPuntos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Puntos"));

        javax.swing.GroupLayout panelPuntosLayout = new javax.swing.GroupLayout(panelPuntos);
        panelPuntos.setLayout(panelPuntosLayout);
        panelPuntosLayout.setHorizontalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPunto4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPunto2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPunto3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPuntosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblPunto1, lblPunto2, lblPunto3, lblPunto4});

        panelPuntosLayout.setVerticalGroup(
            panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPuntosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPuntosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPuntosLayout.createSequentialGroup()
                        .addComponent(lblPunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPunto2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPunto3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPunto4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPuntosLayout.createSequentialGroup()
                        .addComponent(lblJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPuntosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblPunto1, lblPunto2, lblPunto3, lblPunto4});

        panelOtros.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));

        cmdJugadoresActivos.setText("Jugadores Activos");
        cmdJugadoresActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJugadoresActivosActionPerformed(evt);
            }
        });

        cmdAcabar.setText("Abandonar Sala");
        cmdAcabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAcabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOtrosLayout = new javax.swing.GroupLayout(panelOtros);
        panelOtros.setLayout(panelOtrosLayout);
        panelOtrosLayout.setHorizontalGroup(
            panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdJugadoresActivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdAcabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOtrosLayout.setVerticalGroup(
            panelOtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOtrosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cmdJugadoresActivos)
                .addGap(18, 18, 18)
                .addComponent(cmdAcabar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addComponent(panelPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelOtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelPuntos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdJugadoresActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJugadoresActivosActionPerformed
if (panelActivos == null) {
            panelActivos = new FormJugadoresActivos();
            panelActivos.setVisible(true);
            System.out.println("era null");
        }
        if (panelActivos != null && !panelActivos.isVisible()) {
            panelActivos.setVisible(true);
            System.out.println("estaba invi");
        }
    }//GEN-LAST:event_cmdJugadoresActivosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtMensaje.getText().length() > 1200) {
            JOptionPane.showMessageDialog(this, "El tamaño del mensaje excede los 1200 caracteres");
        }
        controlador.enviarMensaje(this.txtMensaje.getText());
        this.txtMensaje.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmdAdjuntarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAdjuntarMouseMoved

    }//GEN-LAST:event_cmdAdjuntarMouseMoved

    private void txtMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeActionPerformed
        if (txtMensaje.getText().length() > 1000) {
            JOptionPane.showInternalConfirmDialog(this, "as");
        }
        controlador.enviarMensaje(this.txtMensaje.getText());
        this.txtMensaje.setText("");
    }//GEN-LAST:event_txtMensajeActionPerformed

    private void cmdAcabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAcabarActionPerformed
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
        }
        this.partidoActivo = false;
        if (controlador.acabar()) {
            System.out.println("SI ACABO ESTA COSA");
            this.txtArea.setText(" ");
            if (panelChat != null) {
                panelChat.dispose();
            }
            if (panelAdjuntar!=null) {
                panelAdjuntar.dispose();
            }
            if (panelActivos!=null) {
                panelActivos.dispose();
            }
            sala.acabar();
        }
    }//GEN-LAST:event_cmdAcabarActionPerformed

    private void cmdAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdjuntarActionPerformed
         if (panelAdjuntar == null) {
            panelAdjuntar = new FormAdjuntar();
            panelAdjuntar.setVisible(true);
        }
        if (panelAdjuntar != null && !panelAdjuntar.isVisible()) {
            panelAdjuntar.setVisible(true);
        }        
    }//GEN-LAST:event_cmdAdjuntarActionPerformed

    private void cmdGuardarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarChatActionPerformed
        JFileChooser buscador = new JFileChooser();
        int seleccion = buscador.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File guardar = buscador.getSelectedFile();
                if (guardar.exists()) {
                    System.out.println("existe");
                    return;
                }
                if (controlador.guardarChat(guardar, this.txtArea.getText())) {
                    JOptionPane.showMessageDialog(null, "chat guardado papu");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmdGuardarChatActionPerformed

    private void cmdCargarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCargarChatActionPerformed
        if (panelChat == null) {
            panelChat = new FormChatEmergente();
            panelChat.setVisible(true);
            System.out.println("era null");
        }
        if (panelChat != null && !panelChat.isVisible()) {
            panelChat.setVisible(true);
            System.out.println("estaba invi");
        }
    }//GEN-LAST:event_cmdCargarChatActionPerformed

    private boolean partidoActivo = true;

    private void iniciar(int tam) {
        FormCampo3 x = new FormCampo3(tam);
        this.panelJuego.removeAll();
        int num = 500 - x.getWidth();
        this.panelJuego.setPreferredSize(new Dimension(x.getWidth(), x.getHeight()));
        this.panel.setPreferredSize(new Dimension(x.getWidth() + 17, x.getHeight() + 28));
        this.panelJuego.add(x);
        this.setPreferredSize(new Dimension(1109 - num, this.getHeight()));
        actualizarChat();
        validarGanador();
        pack();
    }

    public void actualizarChat() {
        Thread hilo = new Thread(new Runnable() {
            public void run() {
                try {
                    while (partidoActivo) {

                        String mensaje = controlador.mensaje();
                        if (mensaje != "") {
                            System.out.println("MENSAJE LLEGADO " + mensaje);
                            txtArea.append(mensaje);
                        }
                        System.out.println("ando en infinito la ptamadre");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        });
        hilo.start();
    }

    public void mostrarPuntos() {
        Thread hilo = new Thread(new Runnable() {
            public void run() {
                while (partidoActivo) {
                    try {
                        String[] puntos = controlador.sacarPuntos();
                        switch (puntos.length / 2) {
                            case 1:
                                setJuga(puntos[0], puntos[1], 1);
                                break;
                            case 2:
                                setJuga(puntos[0], puntos[1], 1);
                                setJuga(puntos[2], puntos[3], 2);
                                break;
                            case 3:
                                setJuga(puntos[0], puntos[1], 1);
                                setJuga(puntos[2], puntos[3], 2);
                                setJuga(puntos[4], puntos[5], 3);
                                break;
                            case 4:
                                setJuga(puntos[0], puntos[1], 1);
                                setJuga(puntos[2], puntos[3], 2);
                                setJuga(puntos[4], puntos[5], 3);
                                setJuga(puntos[6], puntos[7], 4);
                                break;
                        }
                        Thread.sleep(1600);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }

            }
        });
        hilo.start();
    }

    private void setJuga(String nombre, String punto, int numero) {

        switch (numero) {
            case 1:
                lblJugador1.setText(nombre);
                lblPunto1.setText(punto);
                break;
            case 2:
                lblJugador2.setText(nombre);
                lblPunto2.setText(punto);
                break;
            case 3:
                lblJugador3.setText(nombre);
                lblPunto3.setText(punto);
                break;
            case 4:
                lblJugador4.setText(nombre);
                lblPunto4.setText(punto);
                break;
        }
    }

    public void validarGanador() {
        Thread Hilo = new Thread(new Runnable() {
            public void run() {
                String ganador = controlador.validarGanador();
                if (ganador != "") {
                    JOptionPane.showMessageDialog(null, ganador);
                    FormJuego.this.lblGanador.setText(ganador);
                }
            }
        });
        Hilo.start();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chat;
    private javax.swing.JButton cmdAcabar;
    private javax.swing.JButton cmdAdjuntar;
    private javax.swing.JButton cmdCargarChat;
    private javax.swing.JButton cmdGuardarChat;
    private javax.swing.JButton cmdJugadoresActivos;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    private javax.swing.JLabel lblPunto1;
    private javax.swing.JLabel lblPunto2;
    private javax.swing.JLabel lblPunto3;
    private javax.swing.JLabel lblPunto4;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelOtros;
    private javax.swing.JPanel panelPuntos;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
    private FormChatEmergente panelChat;
    private FormAdjuntar panelAdjuntar;
    private FormJugadoresActivos panelActivos;
}
