/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.poo2.gui.panel;

import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import ufps.poo2.gui.controlador.Controlador;

/**
 *
 * @author USUARIO
 */
public class FormAdjuntar extends javax.swing.JFrame {

    /**
     * Creates new form FormAdjuntar
     */
    private FormJuego juego;
    private Controlador controlador = new Controlador();

    public FormAdjuntar() {

        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Enviar archivos");
        lblUrl.setText(" ");
        jugadores = new JToggleButton[4];
        jugadores[0] = cmdJugador1;
        jugadores[1] = cmdJugador2;
        jugadores[2] = cmdJugador3;
        jugadores[3] = cmdJugador4;
        block();
        actualizarNombres();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdJugador1 = new javax.swing.JToggleButton();
        cmdJugador2 = new javax.swing.JToggleButton();
        cmdJugador3 = new javax.swing.JToggleButton();
        cmdJugador4 = new javax.swing.JToggleButton();
        cmdAdjuntar = new javax.swing.JButton();
        cmdEnviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblUrl = new javax.swing.JLabel();
        cmdSalir = new javax.swing.JButton();
        txtPuerto = new javax.swing.JTextField();
        lblPuerto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adjuntar"));

        cmdJugador1.setText("Jugador 1");
        cmdJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJugador1ActionPerformed(evt);
            }
        });

        cmdJugador2.setText("Jugador 2");
        cmdJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJugador2ActionPerformed(evt);
            }
        });

        cmdJugador3.setText("Jugador 3");
        cmdJugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJugador3ActionPerformed(evt);
            }
        });

        cmdJugador4.setText("Jugador 4");
        cmdJugador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJugador4ActionPerformed(evt);
            }
        });

        cmdAdjuntar.setText("Adjuntar");
        cmdAdjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdjuntarActionPerformed(evt);
            }
        });

        cmdEnviar.setText("Enviar");
        cmdEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Pasos para enviar un archivo:\n \n1.Seleccione un puerto (numero entre 1023 y 65535)\n\n2.Seleccione el jugador a quien desea enviar. \n\n3.Adjunte el archivo\n \n4.pulse en enviar.");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        txtPuerto.setText("65000");
        txtPuerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuertoKeyTyped(evt);
            }
        });

        lblPuerto.setText("Puerto");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/file.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdJugador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdJugador3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdJugador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(cmdAdjuntar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdJugador1)
                            .addComponent(lblPuerto)
                            .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdSalir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdJugador2)
                            .addComponent(cmdAdjuntar)
                            .addComponent(cmdEnviar)))
                    .addComponent(lblUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdJugador3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdJugador4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAdjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdjuntarActionPerformed
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.FILES_ONLY);
        buscador.showOpenDialog(this);
        File archivo = buscador.getSelectedFile();
        lblUrl.setText(archivo.getAbsolutePath());

    }//GEN-LAST:event_cmdAdjuntarActionPerformed

    private void cmdEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarActionPerformed
        if (txtPuerto.getText().length() < 4 || (Integer.valueOf(txtPuerto.getText()) < 1023 || Integer.valueOf(txtPuerto.getText()) > 65535)) {
            JOptionPane.showMessageDialog(null, "Ingrese un puerto entre el 1023 y 65535", "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (lblUrl.getText().equalsIgnoreCase(" ")) {
            JOptionPane.showMessageDialog(null, "Seleccione un archivo", "Alerta", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            controlador.enviarArchivo(lblUrl.getText(), jugador, Integer.valueOf(txtPuerto.getText()));
            JOptionPane.showMessageDialog(null, "El archivo se esta enviando", "Notificación", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            if (e.getMessage().equalsIgnoreCase("El jugador seleccionado se ha desconectado")) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                block();
                lblUrl.setText(" ");
                jugador = " ";
                deseleccionar();
                actualizarNombres();
                return;
            }
        }
        block();
        lblUrl.setText(" ");
        jugador = " ";
        deseleccionar();

    }//GEN-LAST:event_cmdEnviarActionPerformed

    private void cmdJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJugador1ActionPerformed
        evento(evt);
    }//GEN-LAST:event_cmdJugador1ActionPerformed

    private void cmdJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJugador2ActionPerformed
        evento(evt);
    }//GEN-LAST:event_cmdJugador2ActionPerformed

    private void cmdJugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJugador3ActionPerformed
        evento(evt);
    }//GEN-LAST:event_cmdJugador3ActionPerformed

    private void cmdJugador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJugador4ActionPerformed
        evento(evt);
    }//GEN-LAST:event_cmdJugador4ActionPerformed

    private void txtPuertoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuertoKeyTyped
        char x = evt.getKeyChar();
        if (x < '0' || x > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPuertoKeyTyped

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    @Override
    public void dispose() {
        enJuego = false;
        super.dispose();
    }

    private void deseleccionar() {
        for (int i = 0; i < this.jugadores.length; i++) {
            if (jugadores[i].isSelected()) {
                jugadores[i].setSelected(false);
            } else {
                jugadores[i].setEnabled(true);
            }

        }
    }

    public void evento(ActionEvent evt) {

        JToggleButton boton = (JToggleButton) evt.getSource();
        if (jugador.equalsIgnoreCase(boton.getText())) {
            jugador = " ";
            block2(boton);
            return;
        }
        jugador = boton.getText();
        block2(boton);
    }

    private void block() {
        cmdAdjuntar.setEnabled(!cmdAdjuntar.isEnabled());
        lblPuerto.setEnabled(!lblPuerto.isEnabled());
        txtPuerto.setEnabled(!txtPuerto.isEnabled());
        cmdEnviar.setEnabled(!cmdEnviar.isEnabled());

    }

    public void block2(JToggleButton boton) {
        block();
        for (int i = 0; i < jugadores.length; i++) {
            if (!boton.equals(jugadores[i])) {
                jugadores[i].setEnabled(!jugadores[i].isEnabled());
            }
        }
    }
    private String jugador = " ";
    private boolean enJuego = true;
    private JToggleButton[] jugadores;

    private void actualizarNombres() {
        for (int i = 0; i < jugadores.length; i++) {
            jugadores[i].setVisible(false);
        }
        String[] activos = controlador.sacarNombres();
        for (int i = 0; i < activos.length - 1; i++) {
            jugadores[i].setVisible(true);
            jugadores[i].setText(activos[i]);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdjuntar;
    private javax.swing.JButton cmdEnviar;
    private javax.swing.JToggleButton cmdJugador1;
    private javax.swing.JToggleButton cmdJugador2;
    private javax.swing.JToggleButton cmdJugador3;
    private javax.swing.JToggleButton cmdJugador4;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
