/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.poo2.gui.main;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import ufps.poo2.gui.panel.FormCrear;
import ufps.poo2.gui.panel.FormJuego;
import ufps.poo2.gui.panel.FormJugador;
import ufps.poo2.gui.panel.FormSala;
import ufps.poo2.gui.panel.FormUnirse;

/**
 *
 * @author USUARIO
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setTitle("Trimbiliche");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/icono.png")).getImage());
        iniciar();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelContenedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        jMenuCrear = new javax.swing.JMenuItem();
        jMenuUnirse = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemDatos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout JPanelContenedorLayout = new javax.swing.GroupLayout(JPanelContenedor);
        JPanelContenedor.setLayout(JPanelContenedorLayout);
        JPanelContenedorLayout.setHorizontalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        JPanelContenedorLayout.setVerticalGroup(
            JPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        menu.setText("Menu Principal");

        jMenuCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCrear.setText("Crear Juego");
        jMenuCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCrearActionPerformed(evt);
            }
        });
        menu.add(jMenuCrear);

        jMenuUnirse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuUnirse.setText("Unirse Juego");
        jMenuUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUnirseActionPerformed(evt);
            }
        });
        menu.add(jMenuUnirse);

        menuBar.add(menu);

        jMenu1.setText("Configuracion");

        menuItemDatos.setText("Modificar datos");
        menuItemDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDatosActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemDatos);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCrearActionPerformed
        iniciarCrear();
    }//GEN-LAST:event_jMenuCrearActionPerformed

    private void jMenuUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUnirseActionPerformed
        iniciarUnirse();
    }//GEN-LAST:event_jMenuUnirseActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDatosActionPerformed
        iniciar();
    }//GEN-LAST:event_menuItemDatosActionPerformed

    public void iniciarCrear() {
        block(true);
        FormCrear x = new FormCrear(this);
        this.JPanelContenedor.removeAll();
        this.setSize(x.getSize());
        this.JPanelContenedor.add(x.getContentPane());
        x.dispose();
    }

    public void iniciarUnirse() {
        block(true);
        FormUnirse x = new FormUnirse(this);
        this.JPanelContenedor.removeAll();
        this.setSize(x.getSize());
        this.JPanelContenedor.add(x.getContentPane());
        x.dispose();
    }

    public void iniciarJuego(int tamanio, FormSala s) {
        block(false);
        FormJuego x = new FormJuego(tamanio, s);
        this.JPanelContenedor.removeAll();
        this.setSize(x.getSize());
        this.JPanelContenedor.add(x.getContentPane());
        x.dispose();
        x = null;
    }

    public void iniciarSala(FormUnirse w, FormCrear x) {
        if (w != null) {
            block(false);
            FormSala y = new FormSala(false, w, null);
            this.JPanelContenedor.removeAll();
            this.setSize(y.getSize());
            this.JPanelContenedor.add(y.getContentPane());

            y.dispose();
            this.setLocationRelativeTo(null);
        } else if (x != null) {
            block(false);
            FormSala y = new FormSala(true, null, x);
            this.JPanelContenedor.removeAll();
            this.setSize(y.getSize());
            this.JPanelContenedor.add(y.getContentPane());
            y.dispose();
        }
    }

    public void iniciarFormJugador() {
        FormJugador x = new FormJugador(this);
        this.JPanelContenedor.removeAll();
        this.setSize(x.getSize());
        this.JPanelContenedor.add(x.getContentPane());
        x.dispose();
    }

    private void iniciar() {
        block(false);
        iniciarFormJugador();
    }

    public void block(boolean a) {
        menu.setEnabled(a);
        this.menuItemDatos.setEnabled(a);
    }

//    @Override
//    public void dispose(){
//        Controlador x=new Controlador();
//        
//        System.out.println("cerrado papu");
//    super.dispose();    
//}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e1) {

                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e2) {
                }
            }
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelContenedor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuCrear;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuUnirse;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemDatos;
    // End of variables declaration//GEN-END:variables
}
